version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Если сертификатов еще нет физически на диске, следующую строку лучше закомментировать:
      # - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - wp1
      - wp2

  wp1:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpress
      # Ключи лучше оставить, это хорошо для безопасности
    volumes:
      # Общая папка для картинок
      - ./wp_shared_uploads:/var/www/html/wp-content/uploads

  wp2:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      # Та же самая папка на хосте — вот он, общий волюм!
      - ./wp_shared_uploads:/var/www/html/wp-content/uploads

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      # КРИТИЧЕСКИ ВАЖНО: сохраняем базу данных на диск хоста
      - ./db_data:/var/lib/mysql
